### ISSUE TITLE
GAE sdk 1.9.36 can't be download 

### ISSUE THREAD

**Issue by appleparan** [keima/step-go-appengine-util#1]
This is a part of output of wercker. As you can see, the wercker didn't download sdk properly (recieved is only 221) Today, sdk was updated to 1.9.36 and then this things occurred. I'm not sure what is the problem (this package or google or wercker) but I thought you should know. Weird thing is that I can download sdk at command line with `curl` command manually.

```
Unpacking p7zip-full (9.20.1~dfsg.1-4.1+deb8u1) ...
Setting up p7zip-full (9.20.1~dfsg.1-4.1+deb8u1) ...
lastModified:  / currentTime: 1461027542
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   221  100   221    0     0   1508      0 --:--:-- --:--:-- --:--:--  1513
latest: 1.9.36
appcfg.py found in cache
Removing old sdk dir
Extracting go_appengine_sdk_linux_amd64-1.9.36.zip ...
failed: 7z error
```

**Comment by keima** [comment]
Oops, it's go-appengine-util's mistake :(

Turned out by your log, Some situation such as wercker cache has "fresh"( fetched before within 1 week ) cache(1.9.35) and releasing new gae(1.9.36), script will broken.

Workaround is run "clear cache"(Wercker's Application (job) Setting > Options > Clear Cache).

I'll fix this issue.
Thanks for reporting!

**Comment by keima** [comment]
fixed. https://github.com/keima/step-go-appengine-util/commit/a661912a996c3e8990693888441dc108cd0cf39c
